# Generated by Django 2.2.2 on 2019-08-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('square', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('pics', models.CharField(max_length=20)),
                ('modelddd', models.CharField(max_length=20)),
            ],
        ),
    ]
