# Generated by Django 2.2.2 on 2019-08-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='pics',
            field=models.CharField(max_length=200),
        ),
    ]
